repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^day13/input.txt$
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus, '--application-directories=.:support']
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.4.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
