language: python
python: '3.6'
install: pip install virtualenv
script: make
after_success: make push
branches:
    except:
        - gh-pages
env:
    global:
        # GH_TOKEN
        - secure: "A27X0Ggc9UWsqBJPTuJFw8HasiyCKmcTFvZQhCvI9nRghpdvN9FoGhtD/gd7SDReaiAVpel3YsRyg4f41zUagdmKeMLZ6WnP9Hajv96VT2RRYImZ8uJP6q5t3P3KaWuY88lE3EmxZ/Y4N6IywyWjxHP2ClYTzb6IC4MEkoxcYhsWtzDzF958vLXAFiUCtwJlsBU6uxuIMgAjkOu4COAdis4Tn0s+NYu0y+spnH9kOxJeOdmufPhL7LUIi0XTNRDp7mYlDmxH3ysRGWrEN+VFPrTj4TWYGo2tAwIUJcRObWRy5/bX178fL2TS8lgOYwBcq2aRBZ1osjrOqQoBE6riQW3qO/sHicvqPavE6gmG9zWbDnZBQxgxgo25bYxPgH3LDCbPtQJ7Wb67SnVkEvyuAU6vpuMbboKQN6AMtWHtes+M6/u6i+y5fJnwpf7y94rjYW2sQJ8tSTjc3MrqTXd7lR227e3qo2zM41+qoPySPkW+6nbSJ/EZcdrHbzNqJ3ns7BM1e9ueY5RZEpt1f6kIHjt/jZITcGuHdjP7IWD6KJnopJbUeZ5UNCuSJ/KsMXSN52b1iLFvrGgIo7kYWPksmLQzeqbsc+cM7FDkcN4e2OWCLz4J3AP1+hhZKaVC9YnGJ9AnWGNs3avnOqIH4eXFiEX0Afb+fxOS3G8XdYZBqsk="
cache:
    directories:
        - "$HOME/.cache/pip"
        - "$HOME/.cache/pre-commit"
